# Generated by Django 5.0.14 on 2025-10-29 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_latitude_user_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='confirmation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='confirmation_notes',
            field=models.TextField(blank=True, help_text='Notes from recipient when confirming', null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='confirmed_donor',
            field=models.ForeignKey(blank=True, help_text='Donor confirmed by recipient', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_requests', to='core.donor'),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='traditional_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('MATCHED', 'Matched'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('MATCH_FOUND', 'Match Found'), ('REQUEST_ACCEPTED', 'Request Accepted'), ('REQUEST_REJECTED', 'Request Rejected'), ('DONOR_CONFIRMED', 'Donor Confirmed'), ('DONATION_REMINDER', 'Donation Reminder'), ('SYSTEM_UPDATE', 'System Update')], max_length=20),
        ),
    ]
