# Generated by Django 4.2.11 on 2025-11-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Successful Login'), ('LOGIN_FAILED', 'Failed Login'), ('PASSWORD_CHANGE', 'Password Changed'), ('2FA_ENABLED', '2FA Enabled'), ('2FA_DISABLED', '2FA Disabled'), ('SUSPICIOUS_ACTIVITY', 'Suspicious Activity'), ('RATE_LIMIT_EXCEEDED', 'Rate Limit Exceeded'), ('ACCOUNT_LOCKED', 'Account Locked'), ('ACCOUNT_UNLOCKED', 'Account Unlocked'), ('PASSWORD_CHANGE_FAILED', 'Password Change Failed'), ('2FA_BACKUP_USED', '2FA Backup Used')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='twofactorauth',
            name='is_enabled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='twofactorauth',
            name='secret_key',
            field=models.CharField(max_length=64),
        ),
    ]
